apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: intel-device-plugins
spec:
  chart:
    spec:
      chart: intel-device-plugins-operator
      sourceRef:
        kind: HelmRepository
        name: intel-device-plugins-operator
        namespace: intel-device-plugins
      version: 0.32.1
  interval: 1m0s
  values:
    manager:
      devices:
        gpu: true