apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "6.49.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 24h

  valuesFrom:
    - kind: ConfigMap
      name: loki-values

  install:
    crds: Create
  upgrade:
    crds: CreateReplace

