apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/loki
    type: DirectoryOrCreate
  storageClassName: local-loki
