# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: qbittorrent
#   namespace: media
# spec:
#   chartRef:
#     kind: OCIRepository
#     name: qbittorrent
#     namespace: flux-system
#   interval: 1m
#   values:
#       controllers:
#         main:
#           strategy: Recreate
#           containers:
#             main:
#               image:
#                 repository: ghcr.io/home-operations/qbittorrent
#                 pullPolicy: IfNotPresent
#                 tag: 5.1.0
#               env:
#                 TZ: Europe/Copenhagen
#               # resources:
#               #   requests:
#               #     cpu: 10m
#               #     memory: 256Mi
#               #   limits:
#               #     memory: 2Gi


apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: qbittorrent
      version: '0.4.1'
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
      interval: 10m
  # values:
  #   replicaCount: 2