apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki-stack
      version: "2.10.3"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h

  valuesFrom:
    - kind: ConfigMap
      name: loki-values

  install:
    crds: Create
  upgrade:
    crds: CreateReplace

