apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-nfs-homeassistant-config
  resources:
    requests:
      storage: 5Gi
