apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: "1.5.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: alloy
      interval: 12h

  valuesFrom:
    - kind: ConfigMap
      name: alloy-values

  install:
    crds: Create
  upgrade:
    crds: CreateReplace
