apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-certificate
  namespace: media
spec:
  secretName: sonarr-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - sonarr.mkped.com