apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        
    spec:
      restartPolicy: Always

      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.15.2941-ls285

        ports:
        - containerPort: 8989
          protocol: TCP

        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Europe/Copenhagen"

        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /media/tv
          readOnly: true


      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config-pvc
      - name: tv
        persistentVolumeClaim:
          claimName: media-shared-pvc
