apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-certificate
  namespace: media
spec:
  secretName: prowlarr-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.mkped.com