apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: prowlarr
    namespace: media
  interval: 10m
  values:
    config:
      persistence:
        size: "1Gi"
        volumeName: pv-nfs-prowlarr-config
    ingress:
      enabled: true
      hosts:
        - host: prowlarr.mkped.io
          paths:
            - path: /
              pathType: Prefix
          