apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: prowlarr
      version: '3.0.0'
      sourceRef:
        kind: OCIRepository
        name: prowlarr
        namespace: media
      interval: 10m
  values:
    config:
      persistence:
        size: "1Gi"
        volumeName: pv-nfs-prowlarr-config
    ingress:
      enabled: true
      hosts:
        - host: prowlarr.mkped.io
          paths:
            - path: /
              pathType: Prefix
          