kind: Service
apiVersion: v1
metadata:
  name: jellyfin-svc            
  namespace: media
spec:
  selector:
    app: jellyfin       
  ports:
  - name: web
    port: 8096
    protocol: TCP
    targetPort: 8096
  type: ClusterIP