apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-certificate
  namespace: media
spec:
  secretName: radarr-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - radarr.mkped.com