apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: '1.18.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 10m