apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseer-certificate
  namespace: media
spec:
  secretName: jellyseer-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - jellyseer.mkped.com