apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
        
    spec:
      restartPolicy: Always

      nodeSelector:
        node-role.kubernetes.io/worker: "true"

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000

      containers:
      - name: jellyseer
        image: ghcr.io/seerr-team/seerr:v3.1.0

        ports:
        - containerPort: 5055
          protocol: TCP

        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Copenhagen"

        volumeMounts:
        - name: config
          mountPath: /app/config

      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyseer-config-pvc
