apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-api
  namespace: gateway-system
spec:
  interval: 10m
  chart:
    spec:
      chart: gateway-api
      version: '1.2.1'
      sourceRef:
        kind: HelmRepository
        name: gateway-api
        namespace: gateway-system
      interval: 10m
