apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gateway-api
  namespace: gateway-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/gateway-api/charts
