# nfs-persistent-volumes.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-media
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/media
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-qbittorrent-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/configs/qbittorrent
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-jellyfin-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/configs/jellyfin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-prowlarr-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/configs/prowlarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-sonarr-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/configs/sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-radarr-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/configs/radarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-jellyseer-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/configs/jellyseer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-nvr
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/nvr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-nvr-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.20.22.81
    path: /srv/nfs/configs/frigate