apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-certificate
  namespace: frigate
spec:
  secretName: frigate-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - frigate.mkped.com