apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 10m
  chart:
    spec:
      chart: frigate
      version: '7.8.0'
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: frigate
      interval: 10m
  values:

    resources:
      limits:
        cpu: 2000m
        memory: 1000Mi
        gpu.intel.com/i915: 1
      requests:
        cpu: 100m
        memory: 128Mi
        gpu.intel.com/i915: 1

    ingress:
      enabled: true
      hosts:
        - host: frigate.mkped.com
          paths:
            - path: '/'
              portName: http-auth
    tls:
      - secretName: frigate-certificate-secret
        hosts: 
          - frigate.mkped.com

    config: |
      tls:
        enabled: false

      mqtt:
        enabled: false

      ffmpeg:
        hwaccel_args: preset-intel-qsv-h264

      cameras:
        carport:
          enabled: true
          ffmpeg:
            inputs:
              - path: rtsp://root:2mNxviUytTynqHubFFRc@192.168.1.187/axis-media/media.amp?streamprofile=MaxProfile
                roles:
                  - detect