apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 10m
  chart:
    spec:
      chart: frigate
      version: '7.8.0'
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: frigate
      interval: 10m
  values:

    ingress:
      enabled: true
      hosts:
        - host: frigate.mkped.io
          paths:
            - path: '/'
              portName: http-auth

    config: |
      mqtt:
        enabled: false

      cameras:
        carport: # <--- this will be changed to your actual camera later
          enabled: true
          ffmpeg:
            inputs:
              - path: rtsp://root@2mNxviUytTynqHubFFRc192.168.1.187/axis-media/media.amp?adjustablelivestream=1
                roles:
                  - detect