apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-pvc
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-nfs-nvr
  resources:
    requests:
      storage: 256Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-nfs-nvr-config
  resources:
    requests:
      storage: 1Gi