apiVersion: batch/v1
kind: CronJob
metadata:
  name: automatic-parking-registration
  namespace: automatic-parking-registration
spec:
  schedule: "30 7 * * 1-5"
  timeZone: Europe/Copenhagen
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr-credentials
          containers:
            - name: automatic-parking-registration
              image: ghcr.io/mortenkp91/automatic-parking-registration:v1.1.0
              imagePullPolicy: IfNotPresent
              env:
                - name: LICENSE_PLATE
                  valueFrom:
                    secretKeyRef:
                      name: license-plate
                      key: LICENSE_PLATE
                - name: PHONE_NUMBER
                  valueFrom:
                    secretKeyRef:
                      name: phone-number
                      key: PHONE_NUMBER
                - name: TWILIO_ACCOUNT_SID
                  valueFrom:
                    secretKeyRef:
                      name: twilio-account-sid
                      key: TWILIO_ACCOUNT_SID
                - name: TWILIO_AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: twilio-auth-token
                      key: TWILIO_AUTH_TOKEN
                - name: TWILIO_FROM_NUMBER
                  valueFrom:
                    secretKeyRef:
                      name: twilio-phone-number
                      key: TWILIO_FROM_NUMBER
