apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: license-plate
  namespace: automatic-parking-registration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: license-plate
    creationPolicy: Owner
  data:
    - secretKey: LICENSE_PLATE
      remoteRef:
        key: license-plate
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phone-number
  namespace: automatic-parking-registration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: phone-number
    creationPolicy: Owner
  data:
    - secretKey: PHONE_NUMBER
      remoteRef:
        key: phone-number
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twilio-account-sid
  namespace: automatic-parking-registration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: twilio-account-sid
    creationPolicy: Owner
  data:
    - secretKey: TWILIO_ACCOUNT_SID
      remoteRef:
        key: twilio-account-sid
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twilio-auth-token
  namespace: automatic-parking-registration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: twilio-auth-token
    creationPolicy: Owner
  data:
    - secretKey: TWILIO_AUTH_TOKEN
      remoteRef:
        key: twilio-auth-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twilio-phone-number
  namespace: automatic-parking-registration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: twilio-phone-number
    creationPolicy: Owner
  data:
    - secretKey: TWILIO_FROM_NUMBER
      remoteRef:
        key: twilio-phone-number
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: automatic-parking-registration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"Mortenkp91","password":"{{ .GHCR_READ_TOKEN }}","auth":"{{ printf "%s:%s" "Mortenkp91" .GHCR_READ_TOKEN | b64enc }}"}}}
  data:
    - secretKey: GHCR_READ_TOKEN
      remoteRef:
        key: ghcr-read-token
