apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent
    namespace: flux-system
  interval: 1m
  values:
      controllers:
        main:
          strategy: Recreate
          containers:
            main:
              image:
                repository: ghcr.io/home-operations/qbittorrent
                pullPolicy: IfNotPresent
                tag: 5.1.0
              env:
                TZ: Europe/Copenhagen
              # resources:
              #   requests:
              #     cpu: 10m
              #     memory: 256Mi
              #   limits:
              #     memory: 2Gi