apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 2
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      restartPolicy: Always
      containers:
        - name: qbittorrent
          image: ghcr.io/linuxserver/qbittorrent:5.1.0-r0-ls398
          imagePullPolicy: IfNotPresent

          envFrom:
          - configMapRef:
             name: qbittorrent

          ports:
            - containerPort: 8080
              name: web-ui
              protocol: TCP
            - containerPort: 6881
              name: torrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: torrent-udp
              protocol: UDP

          volumeMounts:
          - name: media
            mountPath: /media
          - name: config
            mountPath: /config

      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-shared-pvc
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
