# jellyfin-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  resources:
    requests:
      storage: 1Ti