apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 10m
  chart:
    spec:
      chart: node-feature-discovery
      version: '0.17.3'
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: node-feature-discovery
      interval: 10m
  # values:
  #   ports:
  #     web:
  #       redirections:
  #         entryPoint:
  #           to: websecure
  #           scheme: https
  #           permanent: true