apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: '1.16.1'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 10m
  values:
    provider:
      name: cloudflare

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: CF_API_TOKEN

    policy: upsert-only
    sources:
      - ingress
    txtOwnerId: homelab
    interval: 1m

    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
