apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-provisioner
  namespace: nfs-subdir-provisioner
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.18'
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-provisioner
        namespace: nfs-subdir-provisioner
      interval: 10m
  values:
    nfs:
      server: 10.20.22.81
      path: /srv/nfs

    storageClass:
      name: nfs-client
      reclaimPolicy: Retain
      # Keeps data on the NFS server when a PVC is deleted (renames with "archived-" prefix)
      archiveOnDelete: "true"
      # Subdirectory naming pattern: <namespace>/<pvc-name>
      pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs\\.io/storage-path:${.PVC.name}}"

    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
