apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-provisioner
  namespace: nfs-subdir-provisioner
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
