apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-shared-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-nfs-media
  resources:
    requests:
      storage: 1.0Ti