apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certificate
  namespace: monitoring
spec:
  secretName: prometheus-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.mkped.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: monitoring
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: cloudfare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.mkped.com